apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: csi-osc-vsc
driver: bsu.csi.outscale.com
deletionPolicy: Delete
parameters:
  exportBucket: "csi-snapshot-exporter"
  exportImageFormat: "qcow2"
  exportPrefix: "{ns}/{vs}/{date}/"
  exportToOOS: "true"
