kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: osc-csi-attacher-binding
  labels:
    {{- include "osc-bsu-csi-driver.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: osc-csi-controller-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: osc-external-attacher-role
  apiGroup: rbac.authorization.k8s.io