# Node Service
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: osc-csi-node
  namespace: kube-system
  labels:
    {{- include "osc-bsu-csi-driver.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: osc-csi-node
      {{- include "osc-bsu-csi-driver.selectorLabels" . | nindent 6 }}
  updateStrategy:
    {{- toYaml .Values.node.updateStrategy | nindent 4 }}
  template:
    metadata:
      labels:
        app: osc-csi-node
        {{- include "osc-bsu-csi-driver.labels" . | nindent 8 }}
        {{- if .Values.node.podLabels }}
          {{ toYaml .Values.node.podLabels | nindent 8 }}
        {{- end }}
      {{- if .Values.node.podAnnotations }}
      annotations: {{ toYaml .Values.node.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      nodeSelector:
        kubernetes.io/os: linux
        {{- with .Values.node.nodeSelector }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      hostNetwork: true
      priorityClassName: system-node-critical
      {{- with .Values.node.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      tolerations:
      {{- if .Values.node.tolerateAllTaints }}
        - operator: Exists
      {{- else }}
        {{- with .Values.node.tolerations }}
{{ toYaml . | indent 8 }}
        {{- end }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: osc-plugin
          image: {{ .Values.driver.image }}:{{ .Values.driver.tag }}
          imagePullPolicy: {{ .Values.driver.imagePullPolicy }}
          args:
            - node
            - --endpoint=$(CSI_ENDPOINT)
            - --logtostderr
            - --v={{ .Values.logs.verbosity }}
          {{- range .Values.node.additionalArgs }}
            - {{ . }}
          {{- end }}
          env:
            - name: CSI_ENDPOINT
              value: unix:/csi/csi.sock
          {{- if .Values.driver.maxBsuVolumes }}
            - name: MAX_BSU_VOLUMES
              value: "{{ .Values.driver.maxBsuVolumes }}"
          {{- end }}
          volumeMounts:
            - name: kubelet-dir
              mountPath: /var/lib/kubelet
              mountPropagation: "Bidirectional"
            - name: plugin-dir
              mountPath: /csi
            - name: device-dir
              mountPath: /dev
          ports:
            - name: healthz
              containerPort: {{ .Values.sidecars.livenessProbe.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 10
            failureThreshold: 5
          {{- with .Values.node.resources }}
          resources: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.node.securityContext }}
          securityContext:  
            {{- toYaml . | nindent 12 }}
          {{- end }}
        - name: node-driver-registrar
          image: {{ .Values.sidecars.nodeDriverRegistrar.image }}:{{ .Values.sidecars.nodeDriverRegistrar.tag }}
          imagePullPolicy: {{ .Values.driver.imagePullPolicy }}
          args:
            - --csi-address=$(ADDRESS)
            - --kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)
            - --v={{ .Values.logs.verbosity }}
          {{- if .Values.sidecars.metrics }}
            - --http-endpoint=:{{ .Values.sidecars.nodeDriverRegistrar.metricsPort }}
          ports:
            - name: httpendpoint
              containerPort: {{ .Values.sidecars.nodeDriverRegistrar.metricsPort }}
              protocol: TCP
          {{- end }}
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: DRIVER_REG_SOCK_PATH
              value: /var/lib/kubelet/plugins/bsu.csi.outscale.com/csi.sock
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
          {{- if .Values.sidecars.nodeDriverRegistrar.resources }}
            {{- with .Values.sidecars.nodeDriverRegistrar.resources }}
          resources: {{ toYaml . | nindent 12 }}
            {{- end }}
          {{- else }}
            {{- with .Values.sidecars.resources }}
          resources: {{ toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- with .Values.sidecars.securityContext }}
          securityContext:  
            {{- toYaml . | nindent 12 }}
          {{- end }}
        - name: liveness-probe
          image: {{ .Values.sidecars.livenessProbe.image }}:{{ .Values.sidecars.livenessProbe.tag }}
          imagePullPolicy: {{ .Values.driver.imagePullPolicy }}
          args:
            - --csi-address=/csi/csi.sock
            - --health-port={{ .Values.sidecars.livenessProbe.port }}
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
          {{- if .Values.sidecars.livenessProbe.resources }}
            {{- with .Values.sidecars.livenessProbe.resources }}
          resources: {{ toYaml . | nindent 12 }}
            {{- end }}
          {{- else }}
            {{- with .Values.sidecars.resources }}
          resources: {{ toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- with .Values.sidecars.securityContext }}
          securityContext:  
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: kubelet-dir
          hostPath:
            path: /var/lib/kubelet
            type: Directory
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/bsu.csi.outscale.com/
            type: DirectoryOrCreate
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: Directory
        - name: device-dir
          hostPath:
            path: /dev
            type: Directory