apiVersion: v1
appVersion: "v1.10.0"
name: osc-bsu-csi-driver
description: A Helm chart for the Outscale BSU CSI Driver
version: 2.0.1
kubeVersion: ">=1.20"
home: https://github.com/outscale/osc-bsu-csi-driver
sources:
  - https://github.com/outscale/osc-bsu-csi-driver
keywords:
  - osc
  - bsu
  - csi
maintainers:
  - name: 3DS Outscale
    email: support@outscale.com
