apiVersion: v1
appVersion: "0.0.10beta"
description: A Helm chart for OSC CCM cloud provider
name: osc-cloud-controller-manager
version: 0.0.3
kubeVersion: ">=1.14.0-0"
home: https://github.com/outscale-dev/cloud-provider-osc/
sources:
  - https://github.com/outscale-dev/cloud-provider-osc/
keywords:
  - osc
  - ows
  - CCM
  - LBU
maintainers:
  - name: 3DS Outscale
    email: support@outscale.com

