# Default values for osc-cloud-controller-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: outscale/cloud-provider-osc
  tag: v0.0.9beta
  pullPolicy: IfNotPresent

verbose: ""
oscSecretName: ""
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
