name: Release Helm

on:
  push:
    tags:
    - 'v*'
  workflow_dispatch:  
    
permissions:
  contents: write

jobs:
  release-helm:
    if: ${{ contains(github.ref, 'helm') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
      - name: Get changelog for release
        id: changelog
        uses: mindsers/changelog-reader-action@32aa5b4c155d76c94e4ec883a223c947b2f02656 # v2
        with:
          path: "CHANGELOG-1.X.md"
          version: ${{ github.ref_name }}
      - uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4
        with:
          version: v3.18.3
      - name : Create Helm package
        run: make helm-package
      - name: Create Release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref_name }}
          name: Helm Release ${{ github.ref_name }}
          draft: true
          prerelease: false
          body: ${{ steps.changelog.outputs.changes }}
          files: out-helm/*